version: "3"

services:
  postgres:
    container_name: tasker-postgres
    image: postgres:14.4-bullseye
    env_file:
      - .env
    volumes:
      - tracker-db:/var/lib/postgresql/data
    restart: always

  tasker-backend:
    container_name: tasker-backend
    image: ${BACKEND_IMAGE}
    build:
      context: ./src
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    restart: always

volumes:
  tracker-db: