name: Deploy
on: 
  push:
    branches:
    - backend

env:
  IMAGE_REGISTRY: ghcr.io/beally-jean/tasker-backend

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: docker/login-action@v1
        name: login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create .env
        run: |
          echo "${{ secrets.DOTENV }}" > .env

      - name: build and push images
        run: |
          IMAGE=${IMAGE_REGISTRY}:${GITHUB_SHA}
          docker image build -t ${IMAGE} .
          docker image push ${IMAGE}

  deploy:
    name: run the app
    runs-on: self-hosted
    needs: 
    - build
    steps:
      - uses: actions/checkout@v2.3.4
        with: 
          submodules: true
      
      - uses: docker/login-action@v1
        name: login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: create .env
        run: |
          echo ${{ secrets.DOTENV }} > .env
          cat .env

      - name: run app
        run: |
          BACKEND_IMAGE=${IMAGE_REGISTRY}:${GITHUB_SHA}
          docker-compose pull
          docker-compose up -d
