name: Deploy
on: 
  push:
    branches:
    - frontend

env:
  IMAGE_REGISTRY: ghcr.io/beally-jean/tasker-frontend
  PROJECT_NAME: tasker-frontend

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: docker/login-action@v1
        name: login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push images
        run: |
          export FRONTEND_IMAGE=${IMAGE_REGISTRY}:${GITHUB_SHA}
          docker-compose --project-name ${PROJECT_NAME} build
          docker-compose --project-name ${PROJECT_NAME} push

  deploy:
    name: run the app
    runs-on: self-hosted
    needs: 
    - build
    steps:
      - uses: actions/checkout@v2.3.4
        with: 
          submodules: true
      
      - uses: docker/login-action@v1
        name: login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: run app
        run: |
          export FRONTEND_IMAGE=${IMAGE_REGISTRY}:${GITHUB_SHA}
          docker-compose --project-name ${PROJECT_NAME} pull
          docker-compose --project-name ${PROJECT_NAME} up -d
